baseurl             = "http://flomotlik.me/"
theme               = "cocoa"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Florian Motlik"
title               = "Florian Motlik"
pluralizelisttitles = false
googleAnalytics     = "UA-52384561-1"

[permalinks]
blog  = "blog/:slug/"

[params]
dateform     = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description  = "Personal Homepage"
logofile = "img/logo.png"
faviconfile  = "img/favicon.ico"
highlightjs  = true
progressively = false
latestpostcount = 5
lang         = "en"
github       = "flomotlik"
email        = "flo@flomotlik.me"
linkedin     = "florianmotlik"
twitter      = "flomotlik"
social_banner = "img/headshot.jpg"
